// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5npUVropH_g6mkoCyN7g8LRLF0SQ6vjw',
    appId: '1:763824604907:web:9c534d16bda65c4472e0ae',
    messagingSenderId: '763824604907',
    projectId: 'weather-f3828',
    authDomain: 'weather-f3828.firebaseapp.com',
    storageBucket: 'weather-f3828.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXFzMYjHUCtmSWXCSs4Rjhe4171-3Lsu8',
    appId: '1:763824604907:android:624c4aba6675df9972e0ae',
    messagingSenderId: '763824604907',
    projectId: 'weather-f3828',
    storageBucket: 'weather-f3828.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDALB2u17MI-etlbTwmXHkO10szbdzZrn0',
    appId: '1:763824604907:ios:cc1dfb68773b1df672e0ae',
    messagingSenderId: '763824604907',
    projectId: 'weather-f3828',
    storageBucket: 'weather-f3828.appspot.com',
    iosClientId: '763824604907-pmdr8ombnqksutqp6gigj8ecei1p47s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDALB2u17MI-etlbTwmXHkO10szbdzZrn0',
    appId: '1:763824604907:ios:c2b487475013d83172e0ae',
    messagingSenderId: '763824604907',
    projectId: 'weather-f3828',
    storageBucket: 'weather-f3828.appspot.com',
    iosClientId: '763824604907-pd8vjrt88b6lpu1t3j1umf8gfp9qn5cb.apps.googleusercontent.com',
    iosBundleId: 'com.example.book.RunnerTests',
  );
}
